import {
  Wrench,
  Zap,
  Droplets,
  Gauge,
  Shield,
  Radius,
  RotateCw,
  Wind,
  Lock,
  AlertTriangle,
  Lightbulb,
  Fuel,
  Check,
  Hammer,
} from "lucide-react";

export const SPECIALTIES = [
  { name: "Engine Repair", slug: "engine-repair", icon: <Wrench className="h-5 w-5" /> },
  { name: "Transmission", slug: "transmission", icon: <Gauge className="h-5 w-5" /> },
  { name: "Electrical", slug: "electrical", icon: <Zap className="h-5 w-5" /> },
  { name: "Oil Change", slug: "oil-change", icon: <Droplets className="h-5 w-5" /> },
  { name: "Brake Service", slug: "brake-service", icon: <Shield className="h-5 w-5" /> },
  { name: "Tire Repair", slug: "tire-repair", icon: <Radius className="h-5 w-5" /> },
  { name: "Battery Service", slug: "battery-service", icon: <Lightbulb className="h-5 w-5" /> },
  { name: "Air Conditioning", slug: "air-conditioning", icon: <Wind className="h-5 w-5" /> },
  { name: "Suspension & Steering", slug: "suspension-steering", icon: <RotateCw className="h-5 w-5" /> },
  { name: "Exhaust System", slug: "exhaust-system", icon: <Fuel className="h-5 w-5" /> },
  { name: "Transmission Fluid", slug: "transmission-fluid", icon: <Droplets className="h-5 w-5" /> },
  { name: "Safety Inspection", slug: "safety-inspection", icon: <Check className="h-5 w-5" /> },
  { name: "General Maintenance", slug: "general-maintenance", icon: <Wrench className="h-5 w-5" /> },
  { name: "Other Services", slug: "other-services", icon: <Hammer className="h-5 w-5" /> },
];